# Makefile for Combinations/src
FLAGS =  -Wfatal-errors -Wall
###FLAGS += -lgmpxx -lgmp
FLAGS += -g

perim : perimeter.cxx Makefile
		g++ perimeter.cxx $(FLAGS) -std=c++20 -o ./perim
		
analyse: analyse.cxx Makefile
	g++ analyse.cxx $(FLAGS) -std=c++20 -o ./an
