# Makefile for Geometric_Triangles_370/src
FLAGS =  -Wfatal-errors -Wall -Wno-unused-variable
FLAGS += -std=c++20
FLAGS += -g

bsoln : b_soln.cxx Makefile
	g++ b_soln.cxx $(FLAGS) -o ./bsoln

asoln : a_soln.cxx Makefile
	g++ a_soln.cxx $(FLAGS) -o ./asoln
		
analyse: analyse.cxx Makefile
	g++ analyse.cxx $(FLAGS) -std=c++20 -o ./an
